language: node_js
node_js:
  - stable
env:
  global:
    - REMOTE_APP_DIR=/var/www/arielsanguinetti.com.ar/
    - REMOTE_USER=deploy
    - REMOTE_HOST=arielsanguinetti.com.ar
cache: yarn
install:
  - yarn
script:
  - yarn test --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
notifications:
  email:
    onfailure: change
    onsuccess: change
