language: node_js
node_js:
  - stable
cache: yarn
install:
  - yarn
script:
  - yarn test --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
notifications:
  email:
    onfailure: change
    onsuccess: change
